import dashboard from './dashboard'
// import others from './others'
import askTavolo from './askTavolo'
import contracts from './contracts'
import customers from './customers'
import email from './email'
// import menuItems from './menuItems'
import messages from './messages'
import orders from './orders'
import profile from './profile'
import schedule from './schedule'
import socialMedia from './socialMedia'
// import templates from './templates'

export default [...dashboard, ...askTavolo, ...email, ...messages, ...customers, ...schedule, ...orders, ...videos, ...socialMedia, ...profile, ...contracts]
